'use client'

import { useState } from 'react'
import { useLocale } from '@/lib/i18n/context'

type Kind = 'web' | 'mixed' | 'code' | 'synthetic'
const records: { name: string; kind: Kind; publisher: string; version: string; url: string; en: string; de: string }[] = [
  { name: 'Common Crawl', kind: 'web', publisher: 'Common Crawl Foundation', version: 'Crawl-ID / snapshot', url: 'https://commoncrawl.org/overview', en: 'An archive of web crawls. The crawl ID and filtering choices define the actual training input. Access to the archive does not establish one licence for all underlying pages.', de: 'Ein Archiv von Web-Crawls. Crawl-ID und Filter bestimmen die tatsächlichen Trainingsdaten. Der Archivzugang belegt keine einheitliche Lizenz für alle enthaltenen Seiten.' },
  { name: 'The Pile', kind: 'mixed', publisher: 'EleutherAI', version: '2020 paper · 825 GiB · 22 subsets', url: 'https://arxiv.org/abs/2101.00027', en: 'A historical English mixture of 22 components. Inspect provenance and rights per component; the original mixture includes Books3. A whole-mixture label such as legitimate obscures these differences.', de: 'Eine historische englische Mischung aus 22 Komponenten. Herkunft und Rechte pro Komponente prüfen; die ursprüngliche Mischung enthält Books3. Ein Gesamtlabel wie legitim verdeckt diese Unterschiede.' },
  { name: 'FineWeb', kind: 'web', publisher: 'Hugging Face', version: '2024 release · 15T tokens', url: 'https://huggingface.co/datasets/HuggingFaceFW/fineweb', en: 'Filtered English Common Crawl text. The release cited here is a historical snapshot, not a claim about the current total. The dataset card documents processing and ODC-By terms; source content rights remain a separate consideration.', de: 'Gefilterter englischer Text aus Common Crawl. Die genannte Veröffentlichung ist ein historischer Stand, keine aktuelle Gesamtgröße. Die Datenkarte dokumentiert Verarbeitung und ODC-By-Bedingungen; Rechte der Quellinhalte sind gesondert zu betrachten.' },
  { name: 'The Stack v2', kind: 'code', publisher: 'BigCode', version: 'v2 · 67.5 TB (full corpus)', url: 'https://huggingface.co/datasets/bigcode/the-stack-v2', en: 'Code sourced through Software Heritage. The full corpus, deduplicated corpus and training subsets have different sizes. Follow the dataset terms and original repository licences; pin a revision because opt-outs change releases.', de: 'Code aus Software Heritage. Vollkorpus, deduplizierter Korpus und Trainings-Teilmengen haben unterschiedliche Größen. Datensatzbedingungen und ursprüngliche Repository-Lizenzen beachten; wegen Opt-outs eine Revision festhalten.' },
  { name: 'Cosmopedia', kind: 'synthetic', publisher: 'Hugging Face', version: 'v0.1 · 2024', url: 'https://huggingface.co/datasets/HuggingFaceTB/cosmopedia', en: 'Synthetic educational text generated using Mixtral. Record generator, prompts, seed sources and validation. Synthetic describes how data was produced, not its quality or legal status.', de: 'Mit Mixtral erzeugte synthetische Lehrtexte. Generator, Prompts, Ausgangsquellen und Validierung dokumentieren. Synthetisch beschreibt die Herstellung, nicht Qualität oder Rechtsstatus.' },
]
export function DataSourceExplorer() {
  const { locale } = useLocale()
  const de = locale === 'de'
  const [filter, setFilter] = useState<Kind | 'all'>('all')
  const labels = de ? { all: 'Alle', web: 'Web', mixed: 'Gemischt', code: 'Code', synthetic: 'Synthetisch' } : { all: 'All', web: 'Web', mixed: 'Mixed', code: 'Code', synthetic: 'Synthetic' }
  return <div className="space-y-5">
    <h3 className="text-xl font-semibold">{de ? 'Quellen mit prüfbarer Herkunft' : 'Sources with inspectable provenance'}</h3>
    <p className="text-sm text-muted">{de ? 'Ausgewählte Beispiele, geprüft am 13.09.2026. Größen gehören zum jeweils benannten Stand. Bytes, Dokumente und Tokens sind unterschiedliche Maße; Tokenzahlen hängen vom Encoding ab.' : 'Selected examples, checked on 2026-09-13. Sizes belong to the named release. Bytes, documents and tokens measure different things; token counts depend on the encoding.'}</p>
    <div className="flex flex-wrap gap-2">{(Object.keys(labels) as (Kind | 'all')[]).map(kind => <button key={kind} type="button" aria-pressed={filter === kind} onClick={() => setFilter(kind)} className={`rounded-lg border px-3 py-2 text-sm ${filter === kind ? 'border-cyan-400 text-cyan-200' : 'border-border text-muted'}`}>{labels[kind]}</button>)}</div>
    <div className="grid gap-4 md:grid-cols-2">{records.filter(record => filter === 'all' || record.kind === filter).map(record => <article key={record.name} className="rounded-xl border border-border bg-surface p-5"><h4 className="font-semibold">{record.name}</h4><p className="mt-1 text-xs text-cyan-300">{record.publisher} · {labels[record.kind]}</p><p className="mt-2 font-mono text-xs text-muted">{record.version}</p><p className="mt-3 text-sm leading-relaxed text-muted">{de ? record.de : record.en}</p><a href={record.url} className="mt-3 inline-block text-sm text-cyan-300 underline">{de ? 'Originalquelle / Datenkarte' : 'Original source / dataset card'}</a></article>)}</div>
  </div>
}
