'use client'
import {useState} from 'react'

const cases={
  de:[
    {name:'Code',a:'Eine Funktion schreiben, die die sichtbaren Beispiele erfüllt.',b:'Dieselbe Funktion mit leeren Eingaben, Unicode und ungültigen Daten korrekt betreiben.',check:'Getrennte Tests für normale Fälle und Randfälle. Ein bestandener Beispieltest sagt nichts über nicht getestete Eingaben.',change:'Neue Testdaten bei unverändertem Modell und Prompt.'},
    {name:'Dokumente',a:'Eine Antwort aus einer klar markierten Passage entnehmen.',b:'Dieselbe Frage zwischen ähnlichen, veralteten und widersprüchlichen Quellen beantworten.',check:'Antwort und Quellenbeleg prüfen. Ein flüssiger Text kann auf der falschen Dokumentversion beruhen.',change:'Relevante Quelle beibehalten, Ablenkungen und Versionen gezielt variieren.'},
    {name:'Bild und Zeichen',a:'Ein Gerät auf einem Foto beschreiben.',b:'Seine Seriennummer einschließlich ähnlicher Zeichen exakt übertragen.',check:'Beschreibung und zeichengetreue Übertragung sind unterschiedliche Zielgrößen. OCR oder ein Crop kann den zweiten Fall unterstützen.',change:'Gleiches Bild mit und ohne hochauflösenden Ausschnitt vergleichen.'},
    {name:'Browser',a:'Beschreiben, wie ein Formular auszufüllen ist.',b:'Das Formular in einer konkreten Sitzung mit Fehlermeldungen und Dialogen erfolgreich ausfüllen.',check:'Den gespeicherten Endzustand prüfen, nicht nur den Plan oder einen Klick.',change:'Gleiche Aufgabe mit unterschiedlichen Startzuständen und Wiederherstellungsfällen.'},
  ],
  en:[
    {name:'Code',a:'Write a function that passes the visible examples.',b:'Run that function correctly on empty inputs, Unicode and invalid data.',check:'Test ordinary and edge cases separately. Passing examples says nothing about untested inputs.',change:'New test inputs with the same model and prompt.'},
    {name:'Documents',a:'Extract an answer from a clearly marked passage.',b:'Answer the same question among similar, outdated and conflicting sources.',check:'Check both the answer and supporting source. Fluent text can rely on the wrong document version.',change:'Keep the relevant source and vary distractors and versions.'},
    {name:'Images and characters',a:'Describe a device in a photograph.',b:'Copy its serial number exactly, including similar-looking characters.',check:'Description and exact transcription have different success criteria. OCR or a crop may help the latter.',change:'Compare the same image with and without a high-resolution crop.'},
    {name:'Browser',a:'Describe how to complete a form.',b:'Complete the form in a live session with errors and dialogs.',check:'Inspect the saved final state, not just a plan or click.',change:'Use the same task with different initial states and recovery cases.'},
  ],
}
export function JaggedFrontierMap({locale='en'}:{locale?:'en'|'de'}) {
 const de=locale==='de';const [selected,setSelected]=useState(0);const items=cases[locale];const item=items[selected]
 return <section className="rounded-2xl border border-border p-4 sm:p-6 space-y-5"><h2 className="text-xl font-semibold">{de?'Ähnliche Aufgaben, andere Erfolgskriterien':'Similar tasks, different success criteria'}</h2><p className="text-sm text-muted">{de?'Ein Evaluationsplan, keine gemessene Fähigkeitskarte. Diese Paare zeigen, warum man Erfolg in einer Aufgabe nicht auf eine benachbarte übertragen sollte. Welches Modell wo scheitert, muss gemessen werden.':'An evaluation plan, not a measured capability map. These pairs show why success on one task should not be assumed on its neighbor. Which model fails where must be measured.'}</p><div className="flex flex-wrap gap-2">{items.map((x,i)=><button key={x.name} aria-pressed={selected===i} className={`min-h-11 px-4 rounded-lg border ${selected===i?'border-primary bg-primary/10':'border-border'}`} onClick={()=>setSelected(i)}>{x.name}</button>)}</div><div className="grid sm:grid-cols-2 gap-4"><div className="rounded-lg border border-border p-4"><h3 className="text-xs text-muted mb-2">{de?'Aufgabe A':'Task A'}</h3><p>{item.a}</p></div><div className="rounded-lg border border-border p-4"><h3 className="text-xs text-muted mb-2">{de?'Aufgabe B':'Task B'}</h3><p>{item.b}</p></div></div><p className="text-sm text-muted"><strong className="text-text">{de?'Prüfung: ':'Check: '}</strong>{item.check}</p><p className="text-sm text-muted"><strong className="text-text">{de?'Kontrollierter Vergleich: ':'Controlled comparison: '}</strong>{item.change}</p></section>
}
